# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  branch = "master"
  name = "github.com/bcmi-labs/arduino-modules"

[[constraint]]
  name = "github.com/blang/semver"
  version = "3.5.1"

[[constraint]]
  name = "github.com/codeclysm/cc"
  version = "1.2.2"

[[constraint]]
  name = "github.com/codeclysm/extract"
  version = "1.1.1"

[[constraint]]
  name = "github.com/dave/jennifer"
  version = "0.17.0"

[[constraint]]
  branch = "master"
  name = "github.com/dmotylev/goproperties"

[[constraint]]
  branch = "master"
  name = "github.com/facchinm/go-serial-native"

[[constraint]]
  branch = "master"
  name = "github.com/getlantern/systray"

[[constraint]]
  name = "github.com/goadesign/goa"
  version = "1.3.1"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/kardianos/osext"

[[constraint]]
  name = "github.com/mattn/go-shellwords"
  version = "1.0.3"

[[constraint]]
  branch = "master"
  name = "github.com/oleksandr/bonjour"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  branch = "master"
  name = "github.com/skratchdot/open-golang"

[[constraint]]
  branch = "master"
  name = "github.com/xrash/smetrics"

[[constraint]]
  branch = "master"
  name = "go.bug.st/serial.v1"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[override]]
  name = "github.com/satori/go.uuid"
  revision = "master"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
