basePath: /
consumes:
- application/json
definitions:
  ArduinoAgentCommand:
    description: A command that the arduino-create-agent can perform on the machine
      (default view)
    example:
      id: upload:arduino:avr:uno
      params:
      - upload.verbose
      - serial.port
      - build.path
      - build.project_name
      pattern: '"{runtime.tools.avrdude.path}/bin/avrdude" "-C{runtime.tools.avrdude.path}/etc/avrdude.conf"
        {upload.verbose}  -patmega328p -carduino -P{serial.port} -b115200 -D "-Uflash:w:{build.path}/{build.project_name}.hex:i"'
    properties:
      id:
        description: A unique identifier for the command
        example: upload:arduino:avr:uno
        type: string
      params:
        description: The command that will be executed
        example:
        - upload.verbose
        - serial.port
        - build.path
        - build.project_name
        items:
          example: Mollitia aut iusto.
          type: string
        type: array
      pattern:
        description: The command that will be executed
        example: '"{runtime.tools.avrdude.path}/bin/avrdude" "-C{runtime.tools.avrdude.path}/etc/avrdude.conf"
          {upload.verbose}  -patmega328p -carduino -P{serial.port} -b115200 -D "-Uflash:w:{build.path}/{build.project_name}.hex:i"'
        type: string
    required:
    - id
    - pattern
    - params
    title: 'Mediatype identifier: application/vnd.arduino.agent.command+json; view=default'
    type: object
  ArduinoAgentCommandCollection:
    description: ArduinoAgentCommandCollection is the media type for an array of ArduinoAgentCommand
      (default view)
    example:
    - id: upload:arduino:avr:uno
      params:
      - upload.verbose
      - serial.port
      - build.path
      - build.project_name
      pattern: '"{runtime.tools.avrdude.path}/bin/avrdude" "-C{runtime.tools.avrdude.path}/etc/avrdude.conf"
        {upload.verbose}  -patmega328p -carduino -P{serial.port} -b115200 -D "-Uflash:w:{build.path}/{build.project_name}.hex:i"'
    - id: upload:arduino:avr:uno
      params:
      - upload.verbose
      - serial.port
      - build.path
      - build.project_name
      pattern: '"{runtime.tools.avrdude.path}/bin/avrdude" "-C{runtime.tools.avrdude.path}/etc/avrdude.conf"
        {upload.verbose}  -patmega328p -carduino -P{serial.port} -b115200 -D "-Uflash:w:{build.path}/{build.project_name}.hex:i"'
    - id: upload:arduino:avr:uno
      params:
      - upload.verbose
      - serial.port
      - build.path
      - build.project_name
      pattern: '"{runtime.tools.avrdude.path}/bin/avrdude" "-C{runtime.tools.avrdude.path}/etc/avrdude.conf"
        {upload.verbose}  -patmega328p -carduino -P{serial.port} -b115200 -D "-Uflash:w:{build.path}/{build.project_name}.hex:i"'
    items:
      $ref: '#/definitions/ArduinoAgentCommand'
    title: 'Mediatype identifier: application/vnd.arduino.agent.command+json; type=collection;
      view=default'
    type: array
  ArduinoAgentDiscover:
    description: ArduinoAgentDiscover media type (default view)
    example:
      network:
      - address: 192.168.1.107
        info: board=Arduino Y\195\186n Shield distro_version=0.1
        name: MyShield
        port: 80
      serial:
      - pid: "0x8036"
        port: /dev/ttyACM0
        serial: Consequatur et.
        vid: "0x2341"
      - pid: "0x8036"
        port: /dev/ttyACM0
        serial: Consequatur et.
        vid: "0x2341"
    properties:
      network:
        $ref: '#/definitions/ArduinoAgentDiscoverNetworkCollection'
      serial:
        $ref: '#/definitions/ArduinoAgentDiscoverSerialCollection'
    required:
    - serial
    - network
    title: 'Mediatype identifier: application/vnd.arduino.agent.discover+json; view=default'
    type: object
  ArduinoAgentDiscoverNetwork:
    description: ArduinoAgentDiscoverNetwork media type (default view)
    example:
      address: 192.168.1.107
      info: board=Arduino Y\195\186n Shield distro_version=0.1
      name: MyShield
      port: 80
    properties:
      address:
        description: IP Address
        example: 192.168.1.107
        type: string
      info:
        description: Informations about the device
        example: board=Arduino Y\195\186n Shield distro_version=0.1
        type: string
      name:
        description: The friendly name given to the device
        example: MyShield
        type: string
      port:
        description: IP Port
        example: 80
        format: int64
        type: integer
    required:
    - address
    - port
    - info
    - name
    title: 'Mediatype identifier: application/vnd.arduino.agent.discover.network+json;
      view=default'
    type: object
  ArduinoAgentDiscoverNetworkCollection:
    description: ArduinoAgentDiscoverNetworkCollection is the media type for an array
      of ArduinoAgentDiscoverNetwork (default view)
    example:
    - address: 192.168.1.107
      info: board=Arduino Y\195\186n Shield distro_version=0.1
      name: MyShield
      port: 80
    - address: 192.168.1.107
      info: board=Arduino Y\195\186n Shield distro_version=0.1
      name: MyShield
      port: 80
    items:
      $ref: '#/definitions/ArduinoAgentDiscoverNetwork'
    title: 'Mediatype identifier: application/vnd.arduino.agent.discover.network+json;
      type=collection; view=default'
    type: array
  ArduinoAgentDiscoverSerial:
    description: ArduinoAgentDiscoverSerial media type (default view)
    example:
      pid: "0x8036"
      port: /dev/ttyACM0
      serial: Consequatur et.
      vid: "0x2341"
    properties:
      pid:
        description: Vendor ID
        example: "0x8036"
        type: string
      port:
        description: The port through which it's connected
        example: /dev/ttyACM0
        type: string
      serial:
        description: The Serial Number
        example: Consequatur et.
        type: string
      vid:
        description: Vendor ID
        example: "0x2341"
        type: string
    required:
    - vid
    - pid
    - port
    title: 'Mediatype identifier: application/vnd.arduino.agent.discover.serial+json;
      view=default'
    type: object
  ArduinoAgentDiscoverSerialCollection:
    description: ArduinoAgentDiscoverSerialCollection is the media type for an array
      of ArduinoAgentDiscoverSerial (default view)
    example:
    - pid: "0x8036"
      port: /dev/ttyACM0
      serial: Consequatur et.
      vid: "0x2341"
    items:
      $ref: '#/definitions/ArduinoAgentDiscoverSerial'
    title: 'Mediatype identifier: application/vnd.arduino.agent.discover.serial+json;
      type=collection; view=default'
    type: array
  ArduinoAgentExec:
    description: The result of the command executed on the machine (default view)
    example:
      status: done
      stderr: Incidunt qui sint voluptatem impedit fuga.
      stdout: Molestiae nisi enim.
    properties:
      status:
        description: The status of the command
        enum:
        - pending
        - done
        example: done
        type: string
      stderr:
        description: The standard error returned by the command
        example: Incidunt qui sint voluptatem impedit fuga.
        type: string
      stdout:
        description: The standard output returned by the command
        example: Molestiae nisi enim.
        type: string
    required:
    - status
    - stdout
    - stderr
    title: 'Mediatype identifier: application/vnd.arduino.agent.exec+json; view=default'
    type: object
  ArduinoAgentManageInfo:
    description: ArduinoAgentManageInfo media type (default view)
    example:
      revision: 4e498c5afc6304b6dc7a74534dbff96015954d48
      version: v1.0.0
    properties:
      revision:
        description: Revision
        example: 4e498c5afc6304b6dc7a74534dbff96015954d48
        type: string
      version:
        description: Version
        example: v1.0.0
        type: string
    required:
    - version
    - revision
    title: 'Mediatype identifier: application/vnd.arduino.agent.manage.info+json;
      view=default'
    type: object
  ArduinoAgentToolsTool:
    description: ArduinoAgentToolsTool media type (default view)
    example:
      name: avrdude
      packager: packager
      path: ~/.arduino/create/avrdude/latest
      version: latest
    properties:
      name:
        description: Name of the installed tool
        example: avrdude
        type: string
      packager:
        description: Packager of the installed tool
        example: packager
        type: string
      path:
        description: Path of the installed tool
        example: ~/.arduino/create/avrdude/latest
        type: string
      version:
        description: Version of the installed tool
        example: latest
        type: string
    required:
    - path
    - name
    - version
    - packager
    title: 'Mediatype identifier: application/vnd.arduino.agent.tools.tool+json; view=default'
    type: object
  ArduinoAgentToolsToolCollection:
    description: ArduinoAgentToolsToolCollection is the media type for an array of
      ArduinoAgentToolsTool (default view)
    example:
    - name: avrdude
      packager: packager
      path: ~/.arduino/create/avrdude/latest
      version: latest
    - name: avrdude
      packager: packager
      path: ~/.arduino/create/avrdude/latest
      version: latest
    items:
      $ref: '#/definitions/ArduinoAgentToolsTool'
    title: 'Mediatype identifier: application/vnd.arduino.agent.tools.tool+json; type=collection;
      view=default'
    type: array
  ExecCommandsV1Payload:
    example:
    - name: serial.port
      value: /dev/ttyACM0
    - name: serial.port
      value: /dev/ttyACM0
    items:
      $ref: '#/definitions/command.param'
    title: ExecCommandsV1Payload
    type: array
  command.param:
    description: Option for the command to execute
    example:
      name: serial.port
      value: /dev/ttyACM0
    properties:
      name:
        description: The name of the param
        example: serial.port
        type: string
      value:
        description: The value of the option
        example: /dev/ttyACM0
        type: string
    title: command.param
    type: object
  tool.download:
    example:
      checksum: SHA-256:71117cce0096dad6c091e2c34eb0b9a3386d3aec7d863d2da733d9e5eac3a6b1
      name: avrdude
      packager: arduino
      signature: 2d701b4efbc8cec62dc299cde01730c5eebcf23d7e4393db8cf7744a9bf1d3de
      url: http://downloads.arduino.cc/tools/avrdude-6.0.1-arduino2-x86_64-pc-linux-gnu.tar.bz2
      version: 6.0.1-arduino2
    properties:
      checksum:
        description: The checksum of the tool to download
        example: SHA-256:71117cce0096dad6c091e2c34eb0b9a3386d3aec7d863d2da733d9e5eac3a6b1
        type: string
      name:
        description: Name of the tool
        example: avrdude
        type: string
      packager:
        description: Packager of the tool
        example: arduino
        type: string
      signature:
        description: The signature of the url of the tool
        example: 2d701b4efbc8cec62dc299cde01730c5eebcf23d7e4393db8cf7744a9bf1d3de
        type: string
      url:
        description: Url of the tool to download
        example: http://downloads.arduino.cc/tools/avrdude-6.0.1-arduino2-x86_64-pc-linux-gnu.tar.bz2
        type: string
      version:
        description: Version of the tool
        example: 6.0.1-arduino2
        type: string
    required:
    - packager
    - name
    - version
    - url
    - checksum
    - signature
    title: tool.download
    type: object
  upload.serial:
    description: The necessary info to upload a sketch over a serial port
    example:
      bin: QmFzZTY0IGlzIGEgZ2VuZ...
      command: upload:arduino:avr:uno
      filename: QmFzZTY0IGlzIGEgZ2VuZ...
      params:
      - name: serial.port
        value: /dev/ttyACM0
      port: /dev/ttyACM0
    properties:
      bin:
        description: Base64-encoded binary file
        example: QmFzZTY0IGlzIGEgZ2VuZ...
        type: string
      command:
        description: The id of the command to use (See commands#list)
        example: upload:arduino:avr:uno
        type: string
      filename:
        description: The name of the binary file
        example: QmFzZTY0IGlzIGEgZ2VuZ...
        type: string
      params:
        description: Params
        example:
        - name: serial.port
          value: /dev/ttyACM0
        items:
          $ref: '#/definitions/command.param'
        type: array
      port:
        description: The serial port
        example: /dev/ttyACM0
        type: string
    title: upload.serial
    type: object
host: localhost:9000
info:
  description: A bridge from the user's computer and the Create platform
  title: Arduino Create Agent
  version: ""
paths:
  /:
    get:
      description: List the commands that the arduino-create-agent can perform on
        the machine
      operationId: commands_v1#list
      produces:
      - application/vnd.arduino.agent.command+json; type=collection
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ArduinoAgentCommandCollection'
      schemes:
      - http
      summary: list commands_v1
      tags:
      - commands_v1
  /{id}:
    get:
      description: Retrieve the status of a running command
      operationId: commands_v1#show
      parameters:
      - in: path
        name: id
        required: true
        type: string
      produces:
      - application/vnd.arduino.agent.exec+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ArduinoAgentExec'
      schemes:
      - http
      summary: show commands_v1
      tags:
      - commands_v1
    post:
      description: Execute a command. Note that if you want to upload a sketch you'll
        probably be better off with the upload api. This one is very low-level
      operationId: commands_v1#exec
      parameters:
      - description: The id of the command
        in: path
        name: id
        required: true
        type: string
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/ExecCommandsV1Payload'
      responses:
        "202":
          description: Accepted
          headers:
            Location:
              description: Contains the location of the show resource
              type: string
      schemes:
      - http
      summary: exec commands_v1
      tags:
      - commands_v1
  /v1/connect:
    get:
      description: Opens a websocket connection to the device, allowing to read/write
      operationId: connect_v1#websocket
      parameters:
      - default: 9600
        description: The speed of the connection. Defaults to 9600
        in: query
        name: baud
        required: true
        type: integer
      - description: The port where the device resides
        in: query
        name: port
        required: true
        type: string
      responses:
        "101":
          description: Switching Protocols
        "400":
          description: Bad Request
      schemes:
      - ws
      summary: websocket connect_v1
      tags:
      - connect_v1
  /v1/discover:
    get:
      description: Returns a list of devices connected to the PC
      operationId: discover_v1#list
      produces:
      - application/vnd.arduino.agent.discover+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ArduinoAgentDiscover'
      schemes:
      - http
      summary: list discover_v1
      tags:
      - discover_v1
  /v1/manage/info:
    get:
      description: Returns the info about the agent
      operationId: manage_v1#info
      produces:
      - application/vnd.arduino.agent.manage.info+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ArduinoAgentManageInfo'
      schemes:
      - http
      summary: info manage_v1
      tags:
      - manage_v1
  /v1/manage/pause:
    post:
      description: Restarts the agent in hibernation mode
      operationId: manage_v1#pause
      produces:
      - text/plain
      responses:
        "200":
          description: OK
      schemes:
      - http
      summary: pause manage_v1
      tags:
      - manage_v1
  /v1/manage/update:
    post:
      description: Search for a new version, updates and restarts itself
      operationId: manage_v1#update
      produces:
      - text/plain
      responses:
        "200":
          description: OK
      schemes:
      - http
      summary: update manage_v1
      tags:
      - manage_v1
  /v1/tools/:
    get:
      description: Show the installed tools
      operationId: tools_v1#list
      produces:
      - application/vnd.arduino.agent.tools.tool+json; type=collection
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ArduinoAgentToolsToolCollection'
      schemes:
      - http
      summary: list tools_v1
      tags:
      - tools_v1
    post:
      description: Downloads a tool in the system
      operationId: tools_v1#download
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/tool.download'
      produces:
      - application/vnd.arduino.agent.tools.tool+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ArduinoAgentToolsTool'
      schemes:
      - http
      summary: download tools_v1
      tags:
      - tools_v1
  /v1/upload:
    post:
      description: Performs an upload of a sketch over the serial port
      operationId: upload_v1#serial
      parameters:
      - description: The necessary info to upload a sketch over a serial port
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/upload.serial'
      responses:
        "202":
          description: Accepted
          headers:
            Location:
              description: Contains the location of the show resource
              type: string
      schemes:
      - http
      summary: serial upload_v1
      tags:
      - upload_v1
  /v1/upload/{id}:
    get:
      description: Retrieve the status of a running command
      operationId: upload_v1#show
      parameters:
      - in: path
        name: id
        required: true
        type: string
      produces:
      - application/vnd.arduino.agent.exec+json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ArduinoAgentExec'
        "404":
          description: Not Found
      schemes:
      - http
      summary: show upload_v1
      tags:
      - upload_v1
produces:
- application/json
responses:
  BadRequest:
    description: Bad Request
  NotFound:
    description: Not Found
  OK:
    description: OK
  SwitchingProtocols:
    description: Switching Protocols
schemes:
- http
swagger: "2.0"
